{
 "title": "HTTP APIs",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "broadcast-service, discovery-service, history-service,  settings-service, user-service,"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Requests/Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "floor(increase(jetty_requests_total{job=\"$service\"}[$__interval] offset $__interval))",
     "legendFormat": "Inbound Requests"
    },
    {
     "expr": "floor(increase(jetty_responses_total{job=\"$service\"}[$__interval] offset $__interval))",
     "legendFormat": "{{code}} Response"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(explorviz_request_time_sum{job=\"$service\"}[$__interval])/rate(explorviz_request_time_count{job=\"$service\"}[$__interval])",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "API Calls per Minute",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(explorviz_request_time_count{job=\"$service\"}[$__interval])",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  }
 ]
}