{
 "title": "Overview",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Up/Down",
   "type": "gauge",
   "description": "Displays which services are currently up and running",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=~\"broadcast-service|user-service|settings-service|analysis-service|history-service|landscape-service|discovery-service\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Average HTTP-Requests per Minute",
   "type": "graph",
   "description": "Average amount of Requests inbound at a service per minute. ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jetty_requests_total[1m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Host CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Host Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}