language: java

env:
  global:
    - MONGODB_VERSION=4.0.6

services:
  - mongodb
  - docker
  - redis-server

jobs:
  fast_finish: true
  allow_failures:
    - jdk: oraclejdk8
  include:
    - jdk: openjdk8
    - jdk: oraclejdk8
    
    - stage: deploy
      name: "Docker Image: Analysis Service"
      if: (type = push) AND ((branch = dev-1) OR (branch = master))
      jdk: openjdk8
      script: cd analysis-service && ../.travis/docker_push.sh
      
    - stage: deploy
      name: "Docker Image: User Service"
      if: (type = push) AND ((branch = dev-1) OR (branch = master))
      jdk: openjdk8
      script: cd user-service && ../.travis/docker_push.sh
      
    - stage: deploy
      name: "Docker Image: Discovery Service"
      if: (type = push) AND ((branch = dev-1) OR (branch = master))
      jdk: openjdk8
      script: cd discovery-service && ../.travis/docker_push.sh
      
    - stage: deploy
      name: "Docker Image: Landscape Service"
      if: (type = push) AND ((branch = dev-1) OR (branch = master))
      jdk: openjdk8
      script: cd landscape-service && ../.travis/docker_push.sh
    
    - stage: documentation
      name: "Publish documentation"
      if: (type = push) AND (branch = master)
      script: chmod +x .travis/javadoc-push.sh && .travis/javadoc-push.sh
    
before_script:
  - chmod +x .travis/docker_push.sh

before_install:
  - chmod +x .travis/mongoDB_setup.sh
  - .travis/mongoDB_setup.sh
  
branches:
  only:
  - master
  - dev-1
