language: java

services:
  - mongodb
  - docker

jobs:
  fast_finish: true
  allow_failures:
    - jdk: oraclejdk8
  include:
    - stage: test
      jdk: openjdk8
      script: ./gradlew test
    - stage: test
      jdk: oraclejdk8
      script: ./gradlew test
    - stage: deploy
      name: "Docker Image: Analysis"
      if: (branch = dev-1) OR (branch = master)
      jdk: openjdk8
      script: cd analysis && ../.travis/docker_push.sh
    - stage: deploy
      name: "Docker Image: Authentication"
      if: (branch = dev-1) OR (branch = master)
      jdk: openjdk8
      script: cd authentication && ../.travis/docker_push.sh
    - stage: deploy
      name: "Docker Image: Discovery"
      if: (branch = dev-1) OR (branch = master)
      jdk: openjdk8
      # script: cd discovery && ../.travis/docker_push.sh
      script: echo "TODO"
    - stage: deploy
      name: "Docker Image: Landscape"
      if: (branch = dev-1) OR (branch = master)
      jdk: openjdk8
      script: cd landscape && ../.travis/docker_push.sh

before_script:
  - chmod +x .travis/docker_push.sh

#before_script:
#  - chmod +x .travis/push.sh
#  - chmod +x .travis/javadoc-push.sh

#after_success:
#  - .travis/javadoc-push.sh
#  - .travis/push.sh

branches:
  only:
  - master
  - dev-1
