language: java

jdk:
- oraclejdk8
- oraclejdk9
- openjdk8

matrix:
  fast_finish: true
  allow_failures:
  - jdk: oraclejdk9

before_script:
  - chmod +x .travis/push.sh

before_install:

script: gradle build

after_success:
  - .travis/push.sh

branches:
  only:
  - master
