language: java

services:
  - docker

jobs:
  fast_finish: true
  allow_failures:
    - jdk: oraclejdk8
  include:
    - stage: test
      name: "Unit Testing"
      jdk: openjdk8
      script: ./gradlew clean test

    - stage: test
      name: "Unit Testing (oraclejdk8)"
      jdk: oraclejdk8
      script: ./gradlew clean test

    - stage: test
      name: "Integration Testing"
      jdk: openjdk8
      script: ./gradlew clean integrationTest

    - stage: test
      name: "Source Code Analysis"
      jdk: oraclejdk8
      script: ./gradlew checkstyle pmd spotbugs

    - stage: snapshot
      name: "Snapshot Publishing"
      if: (type = push) AND ((branch = dev-1) OR (branch = master))
      jdk: openjdk8
      script: ./gradlew clean landscape-service:landscape-model:uploadArchives settings-service:settings-model:uploadArchives

    - stage: deploy
      name: "Docker Image: Analysis Service"
      if: (type = push) AND ((branch = dev-1) OR (branch = master))
      jdk: openjdk8
      script: cd analysis-service && ../.travis/docker_push.sh
      
    - stage: deploy
      name: "Docker Image: User Service"
      if: (type = push) AND ((branch = dev-1) OR (branch = master))
      jdk: openjdk8
      script: cd user-service && ../.travis/docker_push.sh
      
    - stage: deploy
      name: "Docker Image: Discovery Service"
      if: (type = push) AND ((branch = dev-1) OR (branch = master))
      jdk: openjdk8
      script: cd discovery-service && ../.travis/docker_push.sh
      
    - stage: deploy
      name: "Docker Image: Landscape Service"
      if: (type = push) AND ((branch = dev-1) OR (branch = master))
      jdk: openjdk8
      script: cd landscape-service && ../.travis/docker_push.sh

    - stage: deploy
      name: "Docker Image: History Service"
      if: (type = push) AND ((branch = dev-1) OR (branch = master))
      jdk: openjdk8
      script: cd history-service && ../.travis/docker_push.sh
    
    - stage: deploy
      name: "Docker Image: Broadcast Service"
      if: (type = push) AND ((branch = dev-1) OR (branch = master))
      jdk: openjdk8
      script: cd broadcast-service && ../.travis/docker_push.sh

    - stage: deploy
      name: "Docker Image: Settings Service"
      if: (type = push) AND ((branch = dev-1) OR (branch = master))
      jdk: openjdk8
      script: cd settings-service && ../.travis/docker_push.sh
    
    - stage: documentation
      name: "Publish documentation"
      if: (type = push) AND (branch = master)
      script: chmod +x .travis/javadoc-push.sh && .travis/javadoc-push.sh
    
before_script:
  - chmod +x .travis/docker_push.sh
  
branches:
  only:
  - master
  - dev-1
