language: java

env:
  global:
    - MONGODB_VERSION=4.0.6

services:
  - mongodb
  - docker

jobs:
  fast_finish: true
  allow_failures:
    - jdk: oraclejdk8
  include:
    - jdk: openjdk8
    - jdk: oraclejdk8
    
    - stage: deploy
      name: "Docker Image: Analysis"
      if: (branch = dev-1) OR (branch = master)
      jdk: openjdk8
      script: cd analysis && ../.travis/docker_push.sh
      
    - stage: deploy
      name: "Docker Image: Authentication"
      if: (branch = dev-1) OR (branch = master)
      jdk: openjdk8
      script: cd authentication && ../.travis/docker_push.sh
      
    - stage: deploy
      name: "Docker Image: Discovery"
      if: (branch = dev-1) OR (branch = master)
      jdk: openjdk8
      script: cd discovery && ../.travis/docker_push.sh
      
    - stage: deploy
      name: "Docker Image: Landscape"
      if: (branch = dev-1) OR (branch = master)
      jdk: openjdk8
      script: cd landscape && ../.travis/docker_push.sh
    
    - stage: documentation
      name: "Publish documentation"
      if: (branch = master)
      script: chmod +x .travis/javadoc-push.sh && .travis/javadoc-push.sh
    
before_script:
  - chmod +x .travis/docker_push.sh

before_install:
  - chmod +x .travis/mongoDB_setup.sh
  - .travis/mongoDB_setup.sh
  
branches:
  only:
  - master
  - dev-1
