language: java

services:
  - mongodb
  - docker

jobs:
  fast_finish: true
  allow_failures:
    - jdk: oraclejdk8
  include:
    - stage: test
      jdk: openjdk8
      jdk: oraclejdk8
      script: gradle build javadoc
    - stage: deploy
      jdk: openjdk8
    - stage: deploy
      jdk: openjdk8
      provider: script
      script: ls -la analysis

before_script:
  - chmod +x .travis/push.sh
  - chmod +x .travis/javadoc-push.sh

after_success:
  - .travis/javadoc-push.sh
  - .travis/push.sh

branches:
  only:
  - master
  - dev-1
