language: java

jdk:
- oraclejdk8
- oraclejdk9
- openjdk8

matrix:
  fast_finish: true
  allow_failures:
  - jdk: oraclejdk9

before_script:
  - chmod +x .travis/push.sh
  - chmod +x .travis/javadoc-push.sh

script: gradle build javadoc

after_success:
  - .travis/javadoc-push.sh
  - .travis/push.sh

branches:
  only:
  - master
