language: java

services:
  - mongodb
  - docker

jobs:
  fast_finish: true
  allow_failures:
    - jdk: oraclejdk8
  include:
    - jdk: openjdk8
    - jdk: oraclejdk8
    - stage: deploy
      name: "Docker Image: Analysis"
      jdk: openjdk8
      script: cd analysis && ./docker_push.sh
    - stage: deploy
      name: "Docker Image: Authentication"
      jdk: openjdk8
      script: cd authentication && ./docker_push.sh
    - stage: deploy
      name: "Docker Image: Discovery"
      jdk: openjdk8
      script: cd discovery && ./docker_push.sh
    - stage: deploy
      name: "Docker Image: Landscape"
      jdk: openjdk8
      script: cd landscape && ./docker_push.sh

before_script:
  - chmod +x .travis/docker_push.sh

#before_script:
#  - chmod +x .travis/push.sh
#  - chmod +x .travis/javadoc-push.sh

#after_success:
#  - .travis/javadoc-push.sh
#  - .travis/push.sh

branches:
  only:
  - master
  - dev-1
