language: java

jdk:
- openjdk8
- oraclejdk8

services:
  - mongodb
  - docker

jobs:
  fast_finish: true
  allow_failures:
    - jdk: oraclejdk8
  include:
    - stage: test
      jdk: openjdk8
      jdk: oraclejdk8
      script: gradle build javadoc
    - stage: deploy
      jdk: openjdk8
      script: echo "Hello World" && ls -la

before_script:
  - chmod +x .travis/push.sh
  - chmod +x .travis/javadoc-push.sh

script: gradle build javadoc

after_success:
  - .travis/javadoc-push.sh
  - .travis/push.sh

branches:
  only:
  - master
  - dev-1
