language: java

services:
  - mongodb
  - docker

jobs:
  fast_finish: true
  allow_failures:
    - jdk: oraclejdk8
  include:
    - jdk: openjdk8
    - jdk: oraclejdk8
    - stage: deploy
      name: "Docker Image: Analysis"
      jdk: openjdk8
      script: chmod +x .travis/docker_push_analysis.sh && .travis/docker_push_analysis.sh
    - stage: deploy
      name: "Docker Image: Authentication"
      jdk: openjdk8
      provider: script
      script: echo "TODO"
    - stage: deploy
      name: "Docker Image: Discovery"
      jdk: openjdk8
      provider: script
      script: echo "TODO"
    - stage: deploy
      name: "Docker Image: Landscape"
      jdk: openjdk8
      provider: script
      script: echo "TODO"

#before_script:
#  - chmod +x .travis/push.sh
#  - chmod +x .travis/javadoc-push.sh

#after_success:
#  - .travis/javadoc-push.sh
#  - .travis/push.sh

branches:
  only:
  - master
  - dev-1
