# Start ExplorViz with latest development changes
# Monitored applications can be connected

# Environment Variables are based on the 
# properties file of each service, e.g, 
# https://github.com/ExplorViz/explorviz-backend/blob/dev-1/user-service/src/main/resources/explorviz.properties

version: "3.5"
services:
  landscape-service:
    build: ./landscape-service
    container_name: explorviz-backend-landscape-service
    environment:
      - EXCHANGE_KAFKA_BOOTSTRAP_SERVERS=192.168.178.20:9094
      - EXCHANGE_KAFKA_TOPIC_NAME=landscape-update
    expose:
      - "10135"
    networks: 
      - explorviz
    env_file: 
      - logging.env

  analysis-service:
    build: ./analysis-service
    container_name: explorviz-backend-analysis-service
    ports:
      - "10133:10133"
    networks: 
      - explorviz
    env_file: 
      - logging.env

  discovery-service:
    build: ./discovery-service
    container_name: explorviz-backend-discovery-service
    ports:
      - "8083:8083"
    networks: 
      - explorviz
    env_file: 
      - logging.env

  history-service:
    build: ./history-service
    container_name: explorviz-backend-history-service
    depends_on:
      - mongo-history
    environment:
      - MONGO_HOST=mongo-history
      - EXCHANGE_KAFKA_BOOTSTRAP_SERVERS=192.168.178.20:9094
      - EXCHANGE_KAFKA_TOPIC_NAME=landscape-update
    networks: 
      - explorviz
    ports:
      - 8086:8086
    env_file: 
      - logging.env

  mongo-history:
    image: mongo
    container_name: explorviz-backend-landscape-mongo
    command: mongod --port 27018
    volumes:
       - explorviz-history-mongo-data:/data/db
       - explorviz-history-mongo-configdb:/data/configdb
    expose:
      - "27018"
    networks: 
      - explorviz

volumes:
  explorviz-history-mongo-data:
  explorviz-history-mongo-configdb:

networks:
  explorviz:
    driver: bridge
    name: explorviz
