# Start ExplorViz with latest development changes
# Monitored applications can be connected

# Environment Variables are based on the 
# properties file of each service, e.g, 
# https://github.com/ExplorViz/explorviz-backend/blob/dev-1/user-service/src/main/resources/explorviz.properties

version: "3.5"
services:

  ### ExplorViz Services ###

  user-service:
    build: ./user-service
    container_name: explorviz-backend-user-service
    depends_on:
      - mongo-user
      - kafka
    environment:
      - MONGO_HOST=mongo-user
      - EXCHANGE_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks: 
      - explorviz

  settings-service:
    build: ./settings-service
    container_name: explorviz-backend-settings-service
    depends_on:
      - mongo-settings
      - kafka
    environment:
      - MONGO_HOST=mongo-settings
      - EXCHANGE_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks: 
      - explorviz

  landscape-service:
    build: ./landscape-service
    container_name: explorviz-backend-landscape-service
    depends_on:
      - kafka
    environment:
      - EXCHANGE_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EXCHANGE_KAFKA_TOPIC_NAME=landscape-update
    expose:
      - "10135"
    networks: 
      - explorviz

  broadcast-service:
    build: ./broadcast-service
    container_name: explorviz-backend-broadcast-service
    depends_on:
      - kafka
    environment:
      - EXCHANGE_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EXCHANGE_KAFKA_TOPIC_NAME=landscape-update
    networks: 
      - explorviz

  history-service:
    build: ./history-service
    container_name: explorviz-backend-history-service
    depends_on:
      - mongo-history
      - kafka
    environment:
      - MONGO_HOST=mongo-history
      - EXCHANGE_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EXCHANGE_KAFKA_TOPIC_NAME=landscape-update
    networks: 
      - explorviz

  analysis-service:
    build: ./analysis-service
    container_name: explorviz-backend-analysis-service
    ports:
      - "10133:10133"
    networks: 
      - explorviz

  discovery-service:
    build: ./discovery-service
    container_name: explorviz-backend-discovery-service
    ports:
      - "8083:8083"
    depends_on:
      - id-generator
    networks: 
      - explorviz

  frontend:
    image: explorviz/explorviz-frontend:dev
    container_name: explorviz-frontend
    ports:
      - "8090:80"
    environment:
      - API_ROOT=http://localhost:8090
    depends_on:
      - discovery-service
      - landscape-service
      - analysis-service
      - user-service
      - history-service
    networks: 
      - explorviz

  ### Software Stack ###

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    expose:
      - "2181"
    networks: 
      - explorviz

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks: 
      - explorviz

  id-generator:
    image: redis
    container_name: explorviz-id-generator
    command: ["redis-server", "--appendonly", "yes"]
    expose:
      - "6379"
    volumes:
      - explorviz-id-generator-data:/data
    networks: 
      - explorviz

  mongo-user:
    image: mongo
    container_name: explorviz-backend-user-mongo
    command: mongod --port 27017
    volumes:
       - explorviz-user-mongo-data:/data/db
       - explorviz-user-mongo-configdb:/data/configdb
    expose:
      - "27017"
    networks: 
      - explorviz

  mongo-history:
    image: mongo
    container_name: explorviz-landscape-mongo
    command: mongod --port 27018
    volumes:
       - explorviz-history-mongo-data:/data/db
       - explorviz-history-mongo-configdb:/data/configdb
    expose:
      - "27018"
    networks: 
      - explorviz

  mongo-settings:
    image: mongo
    container_name: explorviz-settings-mongo
    command: mongod --port 27019
    volumes:
      - explorviz-settings-mongo-data:/data/db
      - explorviz-settings-mongo-configdb:/data/configdb
    networks: 
      - explorviz

volumes:
  explorviz-user-mongo-data:
  explorviz-user-mongo-configdb:
  explorviz-history-mongo-data:
  explorviz-history-mongo-configdb:
  explorviz-settings-mongo-data:
  explorviz-settings-mongo-configdb:
  explorviz-id-generator-data:

networks:
  explorviz:
    driver: bridge
    name: explorviz
