scrape_configs:
    # Scrape Prometheus itself every 5 seconds.
    - job_name: 'prometheus'
      scrape_interval: 5s
      static_configs:
        - targets: ['localhost:9090']
  
    # Scrape the Node Exporter every 5 seconds.
    - job_name: 'node'
      scrape_interval: 5s
      static_configs:
        - targets: ['localhost:9100']
    
    - job_name: 'user-service'
      scrape_interval: 5s
      static_configs:
        - targets: ['localhost:8082']

    - job_name: 'settings-service'
      scrape_interval: 5s
      static_configs:
        - targets: ['localhost:8087']

    - job_name: 'history-service'
      scrape_interval: 5s
      static_configs:
        - targets: ['localhost:8086']

    - job_name: 'discovery-service'
      scrape_interval: 5s
      static_configs:
        - targets: ['localhost:8083']
    
    - job_name: 'broadcast-service'
      scrape_interval: 5s
      static_configs:
        - targets: ['localhost:8081']
  