version: "3.2"
services:

  reverse-proxy:
    image: explorviz/reverse-proxy
    container_name: explorviz-reverse-proxy
    network_mode: "host"

  mongo-auth:
    image: mongo
    container_name: explorviz-auth-mongo
    ports:
       - 27017:27017
    volumes:
       - explorviz-auth-mongo-data:/data/db
       - explorviz-auth-mongo-configdb:/data/configdb
    network_mode: "host"

  mongo-landscape:
    image: mongo
    container_name: explorviz-landscape-mongo
    command: mongod --port 27018
    ports:
       - 27018:27018
    volumes:
       - explorviz-landscape-mongo-data:/data/db
       - explorviz-landscape-mongo-configdb:/data/configdb
    network_mode: "host"
    

volumes:
  explorviz-auth-mongo-data:
  explorviz-auth-mongo-configdb:
  explorviz-landscape-mongo-data:
  explorviz-landscape-mongo-configdb:
