# Windows Version 18.06.1-ce-win73 (or newer)
version: "3.2"
services:
  reverse-proxy:
    image: explorviz/reverse-proxy:macos
    container_name: explorviz-reverse-proxy
    ports:
      - 8080:8080
  mongo:
    image: mongo
    container_name: explorviz-auth-mongo
    ports:
      - 27017:27017
    volumes:
       - explorviz-auth-mongo-data:/data/db
       - explorviz-auth-mongo-configdb:/data/configdb

volumes:
  explorviz-auth-mongo-data:
  explorviz-auth-mongo-configdb: