version: "3.2"
services:

  reverse-proxy:
    image: explorviz/reverse-proxy:production
    container_name: explorviz-reverse-proxy
    ports:
      - "8080:8080"

  mongo:
    image: mongo
    container_name: explorviz-backend-auth-mongo
    volumes:
       - explorviz-auth-mongo-data:/data/db
       - explorviz-auth-mongo-configdb:/data/configdb
    expose:
      - "27017"

  authentication:
    image: explorviz/explorviz-backend-authentication:dev
    container_name: explorviz-backend-auth
    depends_on:
      - reverse-proxy
      - mongo
    expose:
      - "8082"
    environment:
      - MONGO_IP=mongo

  landscape:
    image: explorviz/explorviz-backend-landscape:dev
    container_name: explorviz-backend-landscape
    expose:
      - "8081"
      - "10135"

  analysis:
    image: explorviz/explorviz-backend-analysis:dev
    container_name: explorviz-backend-analysis
    ports:
      - "10133:10133"

  discovery:
    image: explorviz/explorviz-backend-discovery:dev
    container_name: explorviz-backend-discovery
    ports:
      - "8083:8083"
    
  frontend:
    image: explorviz/explorviz-frontend:dev
    container_name: explorviz-frontend
    ports:
      - "8090:80"
    environment:
      - API_ROOT=http://localhost:8080

volumes:
  explorviz-auth-mongo-data:
  explorviz-auth-mongo-configdb:
