# Windows Version 18.06.1-ce-win73 (or newer)
version: "3.2"
services:

  reverse-proxy:
    image: "traefik:v2.0.1"
    container_name: "explorviz-reverse-proxy"
    ports:
      - "8080:8080"
    volumes:
      - "./traefik/traefik-static.toml:/etc/traefik/traefik.toml"
      - "./traefik/traefik-dynamic-mac-windows.toml:/etc/traefik/traefik-dynamic.toml"

  mongo-auth:
    image: mongo
    container_name: explorviz-auth-mongo
    ports:
      - 27017:27017
    volumes:
       - explorviz-auth-mongo-data:/data/db
       - explorviz-auth-mongo-configdb:/data/configdb

  mongo-landscape:
    image: mongo
    container_name: explorviz-landscape-mongo
    command: mongod --port 27018
    ports:
       - 27018:27018
    volumes:
       - explorviz-landscape-mongo-data:/data/db
       - explorviz-landscape-mongo-configdb:/data/configdb

  mongo-settings:
    image: mongo
    container_name: explorviz-settings-mongo
    command: mongod --port 27019
    ports:
      - 27019:27019
    volumes:
      - explorviz-settings-mongo-data:/data/db
      - explorviz-settings-mongo-configdb:/data/configdb 

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      
  explorviz-swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - 8001:8080
    env_file:
      - apis.env

volumes:
  explorviz-auth-mongo-data:
  explorviz-auth-mongo-configdb:
  explorviz-landscape-mongo-data:
  explorviz-landscape-mongo-configdb:
  explorviz-settings-mongo-data:
  explorviz-settings-mongo-configdb:
