# Windows Version 18.06.1-ce-win73 (or newer)
version: "3.2"
services:

  reverse-proxy:
    image: explorviz/reverse-proxy:macos
    container_name: explorviz-reverse-proxy
    ports:
      - 8080:8080

  mongo-auth:
    image: mongo
    container_name: explorviz-auth-mongo
    ports:
      - 27017:27017
    volumes:
       - explorviz-auth-mongo-data:/data/db
       - explorviz-auth-mongo-configdb:/data/configdb

  mongo-landscape:
    image: mongo
    container_name: explorviz-landscape-mongo
    command: mongod --port 27018
    ports:
       - 27018:27018
    volumes:
       - explorviz-landscape-mongo-data:/data/db
       - explorviz-landscape-mongo-configdb:/data/configdb

   ids-redis:
    image: redis
    container_name: explorviz-ids-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
        - 6379:6379
    volumes:
        - explorviz-ids-redis:/data

volumes:
  explorviz-auth-mongo-data:
  explorviz-auth-mongo-configdb:
  explorviz-landscape-mongo-data:
  explorviz-landscape-mongo-configdb:
  explorviz-ids-redis: