scrape_configs:
    # Scrape Prometheus itself every 5 seconds.
    - job_name: 'prometheus'
      scrape_interval: 5s
      static_configs:
        - targets: ['localhost:9090']
  
    # Scrape the Node Exporter every 5 seconds.
    - job_name: 'node'
      scrape_interval: 5s
      static_configs:
        - targets: ['prom-node-exporter:9100']