# Static Configuration
[providers]
  [providers.file]
    directory = "/etc/traefik"
    watch = true
    filename = "traefik-dynamic.toml"

[api]
  insecure = true
  dashboard = true

[entryPoints]
  [entryPoints.web]
    address = ":8080"

  [entryPoints.traefik]
      address=":8181"