resourcePackages: # packages to consider
   - net.explorviz.broadcast.server.resources
prettyPrint: true
cacheTTL: 0
openAPI:
   info:
      version: '1.4'
      title: ExplorViz Broadcast Service
      description: Exposes and endpoint for clients to register in order to receive updated landscape object through SSE